# Generated by Django 3.1.1 on 2020-09-17 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataPoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField()),
            ],
            options={
                'ordering': ['time'],
            },
        ),
        migrations.CreateModel(
            name='Race',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='WindData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anemo_time', models.IntegerField()),
                ('speed', models.FloatField()),
                ('angle', models.FloatField()),
                ('datapoint', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.datapoint')),
            ],
        ),
        migrations.CreateModel(
            name='WaterData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('water_time', models.IntegerField()),
                ('speed', models.FloatField()),
                ('datapoint', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.datapoint')),
            ],
        ),
        migrations.CreateModel(
            name='TemperatureData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temp_time', models.IntegerField()),
                ('water_temperature', models.FloatField()),
                ('air_temperature', models.FloatField()),
                ('device_temperature', models.FloatField()),
                ('battery_temperature', models.FloatField()),
                ('datapoint', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.datapoint')),
            ],
        ),
        migrations.CreateModel(
            name='GyroscopeData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gyro_time', models.IntegerField()),
                ('pitch', models.FloatField()),
                ('yaw', models.FloatField()),
                ('roll', models.FloatField()),
                ('datapoint', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.datapoint')),
            ],
        ),
        migrations.CreateModel(
            name='GPSData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gps_time', models.IntegerField()),
                ('gps_date', models.IntegerField()),
                ('latitude', models.FloatField()),
                ('latitude_direction', models.CharField(max_length=3)),
                ('longitude', models.FloatField()),
                ('longitude_direction', models.CharField(max_length=3)),
                ('speed_over_ground', models.FloatField()),
                ('track_angle', models.FloatField()),
                ('horizontal_dilutions', models.FloatField()),
                ('altitude_over_msl', models.FloatField()),
                ('error_of_msl', models.FloatField()),
                ('datapoint', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.datapoint')),
            ],
        ),
        migrations.CreateModel(
            name='AccelerometerData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acc_time', models.IntegerField()),
                ('x', models.FloatField()),
                ('y', models.FloatField()),
                ('z', models.FloatField()),
                ('datapoint', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.datapoint')),
            ],
        ),
    ]
