# Generated by Django 3.1.1 on 2020-09-17 17:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gpsdata',
            name='datapoint',
        ),
        migrations.AddField(
            model_name='datapoint',
            name='gpsdata',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.gpsdata'),
            preserve_default=False,
        ),
    ]
