# Generated by Django 3.1.1 on 2020-09-17 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200917_1317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gpsdata',
            name='altitude_over_msl',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='gpsdata',
            name='error_of_msl',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='gpsdata',
            name='gps_date',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='gpsdata',
            name='gps_time',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='gpsdata',
            name='horizontal_dilutions',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='gpsdata',
            name='latitude',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='gpsdata',
            name='longitude',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='gpsdata',
            name='speed_over_ground',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='gpsdata',
            name='track_angle',
            field=models.FloatField(null=True),
        ),
    ]
