# Generated by Django 3.1.1 on 2020-11-04 00:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20200929_1609'),
    ]

    operations = [
        migrations.AddField(
            model_name='datapoint',
            name='race',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='data_points', to='api.race'),
            preserve_default=False,
        ),
    ]
